"""aggiunge deve_cambiare_password a utente

Revision ID: 0e309ba9cea6
Revises: df29e8872cec
Create Date: 2026-08-30 14:05:53.043421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e309ba9cea6'
down_revision: Union[str, Sequence[str], None] = 'df29e8872cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default aggiunto A MANO: la tabella in produzione ha gia' righe,
    # senza un default il NOT NULL farebbe fallire la migrazione (vedi BRIEF §4.3).
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deve_cambiare_password', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_column('deve_cambiare_password')

    # ### end Alembic commands ###
