"""aggiunge impegni dell agenda

Revision ID: 4b6bb227dddd
Revises: 60a3c26a2c27
Create Date: 2026-09-05 00:33:09.155555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6bb227dddd'
down_revision: Union[str, Sequence[str], None] = '60a3c26a2c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impegni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('luogo', sa.String(), nullable=True),
    sa.Column('inizio', sa.DateTime(), nullable=False),
    sa.Column('fine', sa.DateTime(), nullable=True),
    sa.Column('promemoria_minuti', sa.Integer(), nullable=True),
    sa.Column('promemoria_inviato_il', sa.DateTime(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('macchina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['macchina_id'], ['macchine.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impegni', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impegni_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impegni_inizio'), ['inizio'], unique=False)
        batch_op.create_index(batch_op.f('ix_impegni_utente_id'), ['utente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impegni', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impegni_utente_id'))
        batch_op.drop_index(batch_op.f('ix_impegni_inizio'))
        batch_op.drop_index(batch_op.f('ix_impegni_id'))

    op.drop_table('impegni')
    # ### end Alembic commands ###
