"""aggiunge macchine, sezioni, voci e allegati

Revision ID: 60a3c26a2c27
Revises: a4f113121cb6
Create Date: 2026-09-05 00:14:11.875101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a3c26a2c27'
down_revision: Union[str, Sequence[str], None] = 'a4f113121cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macchine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('organizzazione_id', sa.Integer(), nullable=False),
    sa.Column('reparto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizzazione_id'], ['organizzazioni.id'], ),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparti.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macchine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macchine_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_macchine_reparto_id'), ['reparto_id'], unique=False)

    op.create_table('sezioni_macchina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('macchina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['macchina_id'], ['macchine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sezioni_macchina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sezioni_macchina_id'), ['id'], unique=False)

    op.create_table('voci_macchina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('lavoro', 'modifica', 'analisi', 'informazione', name='tipovoce'), nullable=False),
    sa.Column('stato', sa.Enum('da_fare', 'in_corso', 'fatto', name='statovoce'), nullable=True),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('testo', sa.Text(), nullable=True),
    sa.Column('in_generale', sa.Boolean(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('autore_id', sa.Integer(), nullable=True),
    sa.Column('macchina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autore_id'], ['utenti.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['macchina_id'], ['macchine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voci_macchina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voci_macchina_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voci_macchina_macchina_id'), ['macchina_id'], unique=False)

    op.create_table('voci_sezione',
    sa.Column('voce_id', sa.Integer(), nullable=False),
    sa.Column('sezione_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sezione_id'], ['sezioni_macchina.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voce_id'], ['voci_macchina.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voce_id', 'sezione_id')
    )
    op.create_table('allegati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('autore_id', sa.Integer(), nullable=True),
    sa.Column('macchina_id', sa.Integer(), nullable=True),
    sa.Column('sezione_id', sa.Integer(), nullable=True),
    sa.Column('voce_id', sa.Integer(), nullable=True),
    sa.Column('progetto_id', sa.Integer(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autore_id'], ['utenti.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['macchina_id'], ['macchine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sezione_id'], ['sezioni_macchina.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voce_id'], ['voci_macchina.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allegati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allegati_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allegati_lavoro_id'), ['lavoro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allegati_macchina_id'), ['macchina_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allegati_progetto_id'), ['progetto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allegati_sezione_id'), ['sezione_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allegati_voce_id'), ['voce_id'], unique=False)

    # Colonne nullable: i progetti e i lavori che esistono gia' restano senza
    # macchina collegata, esattamente come sono oggi. Vincoli NOMINATI a mano,
    # altrimenti il downgrade non riuscirebbe a eliminarli.
    with op.batch_alter_table('lavori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macchina_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lavori_macchina_id'), ['macchina_id'], unique=False)
        batch_op.create_foreign_key('fk_lavori_macchina_id', 'macchine',
                                    ['macchina_id'], ['id'], ondelete='SET NULL')

    # NB: l'autogenerate voleva anche eliminare ix_progetti_reparto_id, perche' il
    # modello non dichiarava index=True. E' stato aggiunto al modello e la drop
    # tolta da qui: quell'indice serve a ogni elenco progetti.
    with op.batch_alter_table('progetti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macchina_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_progetti_macchina_id'), ['macchina_id'], unique=False)
        batch_op.create_foreign_key('fk_progetti_macchina_id', 'macchine',
                                    ['macchina_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progetti', schema=None) as batch_op:
        batch_op.drop_constraint('fk_progetti_macchina_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_progetti_macchina_id'))
        batch_op.drop_column('macchina_id')

    with op.batch_alter_table('lavori', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lavori_macchina_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lavori_macchina_id'))
        batch_op.drop_column('macchina_id')

    with op.batch_alter_table('allegati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allegati_voce_id'))
        batch_op.drop_index(batch_op.f('ix_allegati_sezione_id'))
        batch_op.drop_index(batch_op.f('ix_allegati_progetto_id'))
        batch_op.drop_index(batch_op.f('ix_allegati_macchina_id'))
        batch_op.drop_index(batch_op.f('ix_allegati_lavoro_id'))
        batch_op.drop_index(batch_op.f('ix_allegati_id'))

    op.drop_table('allegati')
    op.drop_table('voci_sezione')
    with op.batch_alter_table('voci_macchina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voci_macchina_macchina_id'))
        batch_op.drop_index(batch_op.f('ix_voci_macchina_id'))

    op.drop_table('voci_macchina')
    with op.batch_alter_table('sezioni_macchina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sezioni_macchina_id'))

    op.drop_table('sezioni_macchina')
    with op.batch_alter_table('macchine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macchine_reparto_id'))
        batch_op.drop_index(batch_op.f('ix_macchine_id'))

    op.drop_table('macchine')
    # ### end Alembic commands ###
