"""aggiunge email_verificata a utente

Revision ID: 83f12ce295f0
Revises: c7398a76def9
Create Date: 2026-08-22 15:19:39.231944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f12ce295f0'
down_revision: Union[str, Sequence[str], None] = 'c7398a76def9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utenti', sa.Column('email_verificata', sa.Boolean(), nullable=False,
                                       server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utenti', 'email_verificata')
    # ### end Alembic commands ###
