"""aggiunge reparti e visibilita per reparto

Revision ID: a4f113121cb6
Revises: bb30a1939f26
Create Date: 2026-09-04 23:47:57.246733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f113121cb6'
down_revision: Union[str, Sequence[str], None] = 'bb30a1939f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('organizzazione_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizzazione_id'], ['organizzazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reparti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reparti_id'), ['id'], unique=False)

    op.create_table('membri_reparto',
    sa.Column('reparto_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparti.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reparto_id', 'utente_id')
    )
    # Colonna nullable: i progetti gia' esistenti restano "generali" (reparto_id
    # NULL) e continuano a vedersi come oggi. Nessun server_default necessario.
    # Il vincolo va NOMINATO a mano: Alembic lo genera anonimo e il downgrade
    # non riuscirebbe a eliminarlo (drop_constraint(None) fallisce).
    with op.batch_alter_table('progetti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reparto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_progetti_reparto_id', 'reparti',
                                    ['reparto_id'], ['id'], ondelete='SET NULL')
        # Ogni elenco progetti filtra per reparto: l'indice ripaga subito.
        batch_op.create_index(batch_op.f('ix_progetti_reparto_id'), ['reparto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progetti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progetti_reparto_id'))
        batch_op.drop_constraint('fk_progetti_reparto_id', type_='foreignkey')
        batch_op.drop_column('reparto_id')

    op.drop_table('membri_reparto')
    with op.batch_alter_table('reparti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reparti_id'))

    op.drop_table('reparti')
    # ### end Alembic commands ###
