"""aggiunge data_scadenza a lavoro

Revision ID: bb30a1939f26
Revises: 0e309ba9cea6
Create Date: 2026-08-30 14:09:43.645444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb30a1939f26'
down_revision: Union[str, Sequence[str], None] = '0e309ba9cea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lavori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_scadenza', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lavori', schema=None) as batch_op:
        batch_op.drop_column('data_scadenza')

    # ### end Alembic commands ###
