"""aggiunge completamento a lavoro

Revision ID: c06e2e6511ac
Revises: f4b05eb6d462
Create Date: 2026-08-23 07:29:14.519811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06e2e6511ac'
down_revision: Union[str, Sequence[str], None] = 'f4b05eb6d462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lavori', sa.Column('completato_il', sa.DateTime(), nullable=True))
    op.add_column('lavori', sa.Column('completato_da_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lavori', 'utenti', ['completato_da_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lavori', type_='foreignkey')
    op.drop_column('lavori', 'completato_da_id')
    op.drop_column('lavori', 'completato_il')
    # ### end Alembic commands ###
