"""schema iniziale

Revision ID: c7398a76def9
Revises: 
Create Date: 2026-08-22 12:48:10.085515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7398a76def9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizzazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizzazioni_id'), 'organizzazioni', ['id'], unique=False)
    op.create_table('progetti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('organizzazione_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizzazione_id'], ['organizzazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progetti_id'), 'progetti', ['id'], unique=False)
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('ruolo', sa.Enum('admin', 'caposquadra', 'operatore', name='ruoloutente'), nullable=False),
    sa.Column('organizzazione_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizzazione_id'], ['organizzazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_email'), 'utenti', ['email'], unique=True)
    op.create_index(op.f('ix_utenti_id'), 'utenti', ['id'], unique=False)
    op.create_table('lavori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('stato', sa.Enum('da_fare', 'in_corso', 'in_attesa', 'fatto', name='statolavoro'), nullable=False),
    sa.Column('priorita', sa.Enum('bassa', 'normale', 'alta', 'urgente', name='prioritalavoro'), nullable=False),
    sa.Column('progetto_id', sa.Integer(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('aggiornato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lavori_id'), 'lavori', ['id'], unique=False)
    op.create_table('assegnazioni',
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lavoro_id', 'utente_id')
    )
    op.create_table('commenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testo', sa.String(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('autore_id', sa.Integer(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autore_id'], ['utenti.id'], ),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commenti_id'), 'commenti', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commenti_id'), table_name='commenti')
    op.drop_table('commenti')
    op.drop_table('assegnazioni')
    op.drop_index(op.f('ix_lavori_id'), table_name='lavori')
    op.drop_table('lavori')
    op.drop_index(op.f('ix_utenti_id'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_email'), table_name='utenti')
    op.drop_table('utenti')
    op.drop_index(op.f('ix_progetti_id'), table_name='progetti')
    op.drop_table('progetti')
    op.drop_index(op.f('ix_organizzazioni_id'), table_name='organizzazioni')
    op.drop_table('organizzazioni')
    # ### end Alembic commands ###
