"""aggiunge notifiche in-app

Revision ID: c9dcce1d867a
Revises: 085f69855d88
Create Date: 2026-09-05 09:35:18.935128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dcce1d867a'
down_revision: Union[str, Sequence[str], None] = '085f69855d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifiche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('assegnazione', 'commento', 'impegno', name='tipoavviso'), nullable=False),
    sa.Column('testo', sa.String(), nullable=False),
    sa.Column('letta', sa.Boolean(), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('impegno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['impegno_id'], ['impegni.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifiche', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifiche_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifiche_utente_id'), ['utente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifiche', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifiche_utente_id'))
        batch_op.drop_index(batch_op.f('ix_notifiche_id'))

    op.drop_table('notifiche')
    # ### end Alembic commands ###
