"""aggiunge tabella sotto_attivita

Revision ID: df29e8872cec
Revises: c06e2e6511ac
Create Date: 2026-08-23 07:50:30.913118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df29e8872cec'
down_revision: Union[str, Sequence[str], None] = 'c06e2e6511ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sotto_attivita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testo', sa.String(), nullable=False),
    sa.Column('completata', sa.Boolean(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sotto_attivita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sotto_attivita_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sotto_attivita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sotto_attivita_id'))

    op.drop_table('sotto_attivita')
    # ### end Alembic commands ###
