"""aggiunge link_documento a progetto

Revision ID: f4b05eb6d462
Revises: 83f12ce295f0
Create Date: 2026-08-22 16:28:48.735994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b05eb6d462'
down_revision: Union[str, Sequence[str], None] = '83f12ce295f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progetti', sa.Column('link_documento', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progetti', 'link_documento')
    # ### end Alembic commands ###
